# Generated by Django 5.2.2 on 2025-06-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('email', models.CharField(max_length=123)),
                ('phone', models.CharField(max_length=123)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
