# Generated by Django 5.2.2 on 2025-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('author', models.CharField(max_length=130)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='old_books/')),
                ('seller_name', models.CharField(max_length=130)),
                ('contact', models.CharField(max_length=130)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
