# Generated by Django 5.2.3 on 2025-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='username',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
