# Generated by Django 5.2.3 on 2025-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_loginactivity_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=126, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('login_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
