# Generated by Django 5.2.2 on 2025-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_newuser_alter_loginactivity_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selling',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
