# Generated by Django 5.2.3 on 2025-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_delete_selling_alter_newuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('book_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='book_photos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
