# Generated by Django 5.2.3 on 2025-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='login_time',
        ),
        migrations.AddField(
            model_name='newuser',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
