# Generated by Django 5.2.3 on 2025-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_nuser_delete_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='username',
            field=models.CharField(max_length=126),
        ),
    ]
