# Generated by Django 5.2.2 on 2025-07-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_alter_nuser_email_alter_nuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('credit', 'Credit Card'), ('upi', 'UPI'), ('cash', 'Cash')], max_length=20)),
                ('card_num', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.book')),
            ],
        ),
    ]
