# Generated by Django 5.2.3 on 2025-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
