# Generated by Django 5.2.2 on 2025-07-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0017_alter_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedUser',
        ),
    ]
