# Generated by Django 5.2.3 on 2025-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0025_book_quantity_alter_book_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
