# Generated by Django 5.2.3 on 2025-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0026_book_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='out_of_stock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
