# Generated by Django 5.2.2 on 2025-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0027_book_out_of_stock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
