# Generated by Django 5.2.2 on 2025-11-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0028_cartitem_quantity_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
