# Generated by Django 5.2.2 on 2025-11-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0030_payment_delivery_charges_payment_platform_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbook',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.payment'),
        ),
    ]
